### ISSUE TITLE
How to update the ingress controller deployment.yaml file please?

### ISSUE THREAD

**Issue by lakano** [xetys/hetzner-kube#100]
Hi,

To expose TCP/UDP ports from outside, we need to update the ConfigMap of the ingress controller, so I use « kubectl -n ingress get cm/ingress-nginx-ingress-controller -o yaml > cm.yaml », adding the annotations requirements, and re-inject the yaml file with « kubectl -n ingress apply -f cm.yaml »

It's ok but I also need to add the ports in the « ports: » section of the ingress deployment file. I can export it like that « kubectl -n ingress get pod/ingress-nginx-ingress-controller-z8nqk -o yaml > ing.yaml » but if I add the ports to expose in the section, and trying to re-inject the yaml file with « kubectl -n ingress apply -f ing.yaml » it's denied:
```
« Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
The Pod "ingress-nginx-ingress-controller-z8nqk" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations) »
```

So, as ingress is installed by hetzner-kube, could you please tell how to do please?

**Comment by xetys** [comment]
you cannot modified pods. You should do that in the daemon set (try `kubectl -n ingress get daemonset`)

**Comment by lakano** [comment]
Thanks for the info @xetys ! I've done the output, added the TCP port in the « ports » section, applied it, and this seems to be correctly configured, but this not opening the port, may be I've missed something elsewhere :-/

**Comment by xetys** [comment]
Did you kill the pods? DaemonSets don't to rolling updates, as the default update strategy is 'OnDelete'

**Comment by xetys** [comment]
I think this question is resolved. If not, feel free to give feedback here.
