### ISSUE TITLE
Add documentation on how to build the project

### ISSUE THREAD

**Issue by lfrancke** [xetys/hetzner-kube#107]
As someone who's also never used Go before it'd be fabulous if you could include some documentation on how to actually build the project.

I've tried and failed. dep, GOPATH etc. are all new to me.

A few lines in the README would be great.

**Comment by xetys** [comment]
Actually, there are a few lines about this. If you just want to get the current source doing a `go get -u github.com/xetys/hetzner-kube` is enough. In your $GOPATH/src/github.com/xetys you will then find the repo. Inside this repo, you can do a simple `go build` or `go install` without any issues.

If you have dep installed, even `dep ensure` runs over on a clean machine like a charm. I don't exactly get the issue

**Comment by eliasp** [comment]
And if you set `GOBIN` e.g. to `~/.bin`, `go get -u …` will be enough and the resulting binary will end up there, so you could easily add `~/.bin` to your shell's `$PATH`.

**Comment by lfrancke** [comment]
Thanks guys and sorry for the confusion!

As I said having never used it I thought that go get only downloads. I wasn't aware that it also compiles. I'll try to provide a quick patch that clarifies (in my opinion at least :) ) the comment for people like me.

**Comment by exocode** [comment]
For completion

__Installing Go:__ 
On macOS you can put these lines into `~/.zshrc` or ` ~/.bashrc` (depending on your favourite shell):

```
# Go LANG
# install brew install go
#
export GOPATH=$HOME/Go
export PATH=$PATH:/usr/local/opt/go/libexec/bin
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin
```

If you are using `homebrew` you can install Go by `brew install go` and then `go get -u github.com/xetys/hetzner-kube`

**Comment by xetys** [comment]
That's correct. As this is not an issue of this tool I don't think hetzner-kube's docs are the right place for go setup instructions. It is assumed, that go is installed properly.

**Comment by lfrancke** [comment]
I agree that installing Go does not need to be part of the docs but how to build the project should for those that don't know Go.

Currently it says "get it from source" which to me does not imply building. I'll edit the README to make it clearer for me and then it's up to you to decide.
