### ISSUE TITLE
Integration with Gitlab CI/CD

### ISSUE THREAD

**Issue by RamonSmit** [xetys/hetzner-kube#111]
Hi there, 

Thanks for this super awesome application! It made my life a fair bit easier! 

I have one (migth simple) question. I'm not _that_ familiar with K8S but I see 
your application as a entry level into K8S for me. 

Is there a (good?) way to use your application to setup a environment for Gitlab:
https://docs.gitlab.com/ee/user/project/clusters/#adding-an-existing-kubernetes-cluster

I'm fighting with this for a couple of days, and I'm sure that I am doing something totally wrong. 
Are you willing to help me out for a bit?

Many thanks in advance,
Ramon

**Comment by JohnnyQQQQ** [comment]
I used hetzner-kube to build a cluster that we use with GitLab. You can create a ServiceAccount and bind a Role to it and then just add it to GitLab.

**Comment by RamonSmit** [comment]
Ah thanks for the information! 

Got a weird error: 
```
Something went wrong while installing Helm Tiller
 - Can't start installation process
```

Did you encouter this? Or?

**Comment by xetys** [comment]
Why do you need this? You just can install helm using `hetzner-kube cluster addon install helm`

**Comment by RamonSmit** [comment]
Well, those are the integrations inside of GitLab. Guess it's used for the monitoring stack

**Comment by JohnnyQQQQ** [comment]
You don't need any addon. You just need the ServiceAccount with the right role assigned to it and add it into the "Kubernetes" tab under "CI/CD" in your project. Then you can use the kubernetes environment variables in your CD job to deploy your containers to kubernetes.

https://docs.gitlab.com/ee/user/project/clusters/#adding-an-existing-kubernetes-cluster

**Comment by xetys** [comment]
As this is not hetzner-kube related, I close this
