### ISSUE TITLE
error during placement (resource_unavailable)

### ISSUE THREAD

**Issue by fentas** [xetys/hetzner-kube#112]
Using `hetzner-kube` via `go get -u github.com/xetys/hetzner-kube`

```sh
_@_ ~/g/s/g/x/hetzner-kube> hetzner-kube cluster create --name beta --ssh-key *** --master-server-type cx21 --worker-server-type cx41 --ha-enabled --isolated-etcd --self-hosted --master-count 3 --etcd-count 3 --worker-count 5
2018/05/02 16:04:36 Creating new cluster

NAME:beta
MASTERS: 3
WORKERS: 5
ETCD NODES: 3
HA: true
ISOLATED ETCD: true
Enter passphrase for SSH key /home/_/.ssh/id_rsa: 
2018/05/02 16:04:40 creating server 'beta-etcd-01'...
2018/05/02 16:04:40 loading server 'beta-etcd-01'...
2018/05/02 16:04:40 Created node 'beta-etcd-01' with IP 138.***
2018/05/02 16:04:40 creating server 'beta-etcd-02'...
2018/05/02 16:04:40 loading server 'beta-etcd-02'...
2018/05/02 16:04:40 Created node 'beta-etcd-02' with IP 195.***
2018/05/02 16:04:40 creating server 'beta-etcd-03'...
2018/05/02 16:04:40 loading server 'beta-etcd-03'...
2018/05/02 16:04:40 Created node 'beta-etcd-03' with IP 138.***
2018/05/02 16:04:41 creating server 'beta-master-01'...
2018/05/02 16:04:41 loading server 'beta-master-01'...
2018/05/02 16:04:41 Created node 'beta-master-01' with IP 138.***
2018/05/02 16:04:41 creating server 'beta-master-02'...
2018/05/02 16:04:41 loading server 'beta-master-02'...
2018/05/02 16:04:41 Created node 'beta-master-02' with IP 195.***
2018/05/02 16:04:41 creating server 'beta-master-03'...
2018/05/02 16:04:41 loading server 'beta-master-03'...
2018/05/02 16:04:41 Created node 'beta-master-03' with IP 88.***
2018/05/02 16:04:41 creating server 'beta-worker-01'...
2018/05/02 16:04:42 loading server 'beta-worker-01'...
2018/05/02 16:04:42 Created node 'beta-worker-01' with IP 138.***
2018/05/02 16:04:42 creating server 'beta-worker-02'...
2018/05/02 16:04:42 loading server 'beta-worker-02'...
2018/05/02 16:04:42 Created node 'beta-worker-02' with IP 195.***
2018/05/02 16:04:42 creating server 'beta-worker-03'...
2018/05/02 16:04:42 error during placement (resource_unavailable)
```

If I reduce `worker-count` to 3 it will fail at beta-worker-01... > 2 instances left. What is interesting, one time it had only one instance left. So close :sweat_smile: 
There is no server limit issue (still have plenty).

Thanks a lot.
Also tried it a couple of times. Retried it, it will go through quickly (output above) and deleted all instances and started it again.

**Comment by fentas** [comment]
After reducing `datacenters` only to one (`--datacenters nbg1-dc3`) it worked.

**Comment by xetys** [comment]
I think it is a temporary issue at hetzner. I will watch if more users report this issue, and close it in some day if not.

**Comment by athre0z** [comment]
Probably not an issue of this tool. Various bigger instance types have been unavailable on all data-centers in the past few days (they are grayed out in the UI). I think Hetzner is having some issues keeping up with the success of their cloud service.

**Comment by xetys** [comment]
As it was an outage from hetzner, I close this issue

**Comment by smirnov-mi** [comment]
I'm facing the same issue right now. Did someone get any responce from Hetzner last time?

**Comment by smirnov-mi** [comment]
@mavimo    Very funny. Makes totally sence for a cluster. I'm in contact with them now, they asked "which datacenter you use" - so my reply is "2 servers in each DC dude, it's supposed to be a HA cluster". We'll see..

**Comment by smirnov-mi** [comment]
While still waiting for any reaction from Hetzner, I tried "--datacenters nbg1-dc3" and it also helped. 
(3 Masters + 3 workers)
I also tried "--datacenters nbg1-dc3,hel1-dc2" and it also worked. 
"--datacenters nbg1-dc3,fsn1-dc8" - did NOT work, so I guess fsn1-dc8 has some problems.

**Comment by marzelwidmer** [comment]
I also had the same issue.... And have to add ```--datacenters nbg1-dc3,hel1-dc2```  when I create the cluster ``` hetzner-kube cluster create ```

**Comment by mkozjak** [comment]
Just hit the same issue. For now the `nbg1` location is unavailable. Tried setting datacenter to `nbg1-dc1`, but it didn't work. Probably a Hetzner issue? I hit this directly with Terraform's hcloud_server resource.
