### ISSUE TITLE
How to get hetzner-kube to recognise existing clusters?

### ISSUE THREAD

**Issue by kabudu** [xetys/hetzner-kube#114]
How do you get hetzner-kube to recognise existing clusters?

This is the scenario I have.

On machine A

- Install hetzner-kube
- Add context
- Add SSH Key
- Create Cluster

On machine B

- Install hetzner-kube
- Add context (same as on Machine A)
- Add SSH Key (same as on Machine A)
- ```hetzner-kube cluster list``` => List is empty :(

Is there a way to make hetzner-kube behave like ```git fetch``` where it can query the relevant context and pull in the information?

**Comment by xetys** [comment]
Currently, the tool has no support for that right now. But there is a "hack" you can do. The tool saves its state in `~/.hetzner-kube/config.jon`, where the clusters are in the "clusters" array. 
Doing it this way migrating contexts and clusters should work without any problems. For the SSH keys I would suggest to ignore the fact, that you are importing a key which points to an existing `~/.ssh/id_rsa` which isn't really the key. Just add another one pointing to the proper key or use a unique name/location for it to work cross-machine.

**Comment by kabudu** [comment]
@xetys Thanks for the hack, worked like a charm!

**Comment by JohnnyCrazy** [comment]
@xetys Do you have a workaround if you don't have access to this file anymore? Any way to re-create it maybe?
