### ISSUE TITLE
hetzner-kube cluster addon install ingress fails

### ISSUE THREAD

**Issue by exocode** [xetys/hetzner-kube#126]
When i try to install ingress for loadbalancing as an addon it fails:

```
hetzner-kube cluster addon install  --name demo-cluster nginx-ingress-controller
2018/05/13 10:58:11 installing addon nginx-ingress-controller
2018/05/13 10:58:13 run failed
command:helm install --name ingress --namespace ingress --set rbac.create=true,controller.kind=DaemonSet,controller.service.type=ClusterIP,controller.hostNetwork=true stable/nginx-ingress
stdout:
stderr:Process exited with status 1
```

**Comment by JohnnyQQQQ** [comment]
Did you installed the helm addon prior to this?

**Comment by exocode** [comment]
yes by using 

`hetzner-kube cluster addon install  --name demo-cluster helm`

**Comment by exocode** [comment]
I tried it now on a 1 Node cluster as well on a 3 Node cluster:

Steps to reproduce:

1. `hetzner-kube cluster create --name demo-cluster --ssh-key your@secret_key.local  --master-count 3 --worker-count 3 --ha-enabled`
2.  `hetzner-kube cluster addon install --name demo-cluster helm`
3. `hetzner-kube cluster addon install  --name demo-cluster nginx-ingress-controller
hetzner-kube cluster list  ## FAILED`
4. `hetzner-kube cluster list`
4. `ssh root@MASTER_IP`
5. `helm install --namespace ingress --name ingress --set rbac.create=true,controller.hostNetwork=true,controller.kind=DaemonSet,controller.service.type=ClusterIP stable/nginx-ingress ## WORKED`
