### ISSUE TITLE
Encryption over flannel

### ISSUE THREAD

**Issue by quorak** [xetys/hetzner-kube#128]
Hey guys,

have there been any thoughts about encryption of the network traffic between the workers.
I'm not sure if this is enabled by flannel by default. But wanted to check.
Think this would be important for a production setup.

best

**Comment by pierreozoux** [comment]
In this project, there is first a wireguard VPN that is created, and then all net go thought that VPN.

**Comment by quorak** [comment]
ah perfect. that was my main concern. Maybe we add a notice to the Readme.
