### ISSUE TITLE
Add failover IP script for edge-router worker nodes

### ISSUE THREAD

**Issue by pierreozoux** [xetys/hetzner-kube#13]
# Problem

How to achieve true HA without the help of a cloud LoadBalancer?

# Solution

There are not many solutions, the best we have in Hetzner is probably the [Failover IP](https://wiki.hetzner.de/index.php/Failover/en).

All we need for this to work would be the following:
 - tagging edge nodes `role=edge-router`
 - deploy a pod that would watch the health / readiness of these nodes
 - switch automatically the IP to another heatlhy node in case of unhealthy

**Comment by xetys** [comment]
> How to achieve true HA without the help of a cloud LoadBalancer?

by using nginx ingress controller. When deployed as a DaemonSet it runs on all (specified) nodes. These you can put as multiple A-Records to a single Domain and you will get basic load balancing 

If you want to use kubernetes LoadBalancer feature coupled with Hetzner Failover IP, you should implement the CloudProvider interface from Kubernetes. In other words: to build an integration. The cloud provider would then listen to kubernetes events, such as pending LB services, and add Floating IPs to any healthy node (you don't need extra pods for the health watch, as k8s has its health info already in the api server).

Anyways, this is far out of the scope by this tool. I think the [hetzner cloud controller manager](https://github.com/hetznercloud/hcloud-cloud-controller-manager) is a better place for that, as it already implements cloud provider for different tasks

**Comment by pierreozoux** [comment]
Thanks for the answer.

AFAIK, A-records load balancing is not working in browser, see this [answer](https://serverfault.com/questions/349964/dns-round-robin-do-browsers-stick-to-one-ip-as-long-as-it-is-online#350420)

But I think you are right to say that the cloud controller manager should be the place to implement this feature.

**Comment by xetys** [comment]
the answer is from 12 and since then it looks like changed a bit (check the comments of your link)

"not working" is a discussable statement. It's more accurate to say that this way of load balancing gives nearly zero control, how the balancing is happening or decide based on real loads of the nodes. 
In fact, every time you do a hostname resolve, independent from which tool you do, you will get all IPs in random order. So if 100 browsers ask a domain with 3 IPs, they will be spread quite even over these IPs.

Just to comment that :smile:

**Comment by pierreozoux** [comment]
Ok, I wanted to know for sure:
```
host -a ghost.indie.host
Trying "ghost.indie.host"
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43494
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;ghost.indie.host.		IN	ANY

;; ANSWER SECTION:
ghost.indie.host.	1798	IN	A	5.9.102.20
ghost.indie.host.	1798	IN	A	8.8.8.8

Received 66 bytes from 10.10.12.1#53 in 44 ms
```

Test it from your browser :)

https://ghost.indie.host

**Comment by pierreozoux** [comment]
closing in favor of https://github.com/hetznercloud/hcloud-cloud-controller-manager/issues/6 then.

**Comment by pierreozoux** [comment]
Yes, external DNS is also a good idea, but, not perfect.
Some DNS server will cache the answer for 48h..

**Comment by vladimirfx** [comment]
**Failover IP** management implemented in https://github.com/cit-consulting/hetzner-failoverip-controller .
