### ISSUE TITLE
Is it possible to deploy the master nodes (HA) on distinct datacenters?

### ISSUE THREAD

**Issue by loxy** [xetys/hetzner-kube#142]
When using a HA setting it maybe make sense to use the three different datacenters of Hetzner to be more resistent against disasters, like the recent power failure in Falkenstein. 

So, is it possible (or even useful) to deploy the masters to different datacenters? If yes, how? If not, is it possible to add more masters, like workers?

**Comment by xetys** [comment]
Actually this should be the default behavior. The default configurations
already consists of the two German datacenters and hetzner-kube rotates
them round robin.

Kersten Lorenz <notifications@github.com> schrieb am Do., 7. Juni 2018,
14:31:

**Comment by loxy** [comment]
Ah, ok. Nice. Didn't build the HA cluster yet. Is it possible to include Helsinki also, with a flag or something?

**Comment by JohnnyQQQQ** [comment]
Yes, you can use this flag when creating the cluster

```bash
 --datacenters string         Can be used to filter datacenters by their name (default [nbg1-dc3,fsn1-dc8])
```

**Comment by loxy** [comment]
Ok, now I understand. Great work, guys!
