### ISSUE TITLE
Distributed Storage

### ISSUE THREAD

**Issue by pierreozoux** [xetys/hetzner-kube#16]
Same as Ingress, I think it would be good if we offer a default option.

Yesterday, I setup an (almost) successful cluster (without Let's encrypt), and I used rook.
It was almost straight forward, and it looks like a very viable option for the storage.
The plus are:
 - part of CNCF
 - almost in beta (0.7 is a pre-release)
 - support for:
   - Block Storage (I just tried that)
   - Object Storage
   - Shared File System

Here are some notes I used:
```
git clone https://github.com/rook/rook
cd rook/cluster/examples/kubernetes
kubectl create -f rook-operator.yaml
kubectl create -f rook-cluster.yaml
kubectl create -f rook-storageclass.yaml
kubectl create -f mysql.yaml
kubectl create -f wordpress.yaml
```

The helm chart didn't work, but this way, it wokred.
(didn't have time to debug further the helm, but I think it should be the way to go)

Then I deployed a RocketChat instance, with the official helm chart, and it worked with the storage \o/ (and the ingress, but without tls :/ )

**Comment by xetys** [comment]
Don't get me wrong, I'm a big fan of rook and watching it from April last year.

I think it should be offered as an addon like mentioned in #15

**Comment by Baughn** [comment]
At a minimum, it should be documented.

The 'full tutorial' installs OpenEBS, but doesn't mention that OpenEBS doesn't specify a default storage class by default.

**Comment by pierreozoux** [comment]
ok, the new rook option looks good to me!

I still think we would be better off using an helm chart, event with our specific configuration, but this can be discussed later, once the helm chart is fixed :) .

We can envision that based on the node tags (VMs or [BareMetal](https://github.com/hetznercloud/hcloud-cloud-controller-manager/issues/5)) the rook addon would be configured accordingly with a sane default, and yes, in this sense it makes sense to have an addon :)

I'll close the issue now!

Thanks @xetys for the amazing work! Looks promising!
