### ISSUE TITLE
apt update

### ISSUE THREAD

**Issue by ericrange** [xetys/hetzner-kube#176]
N: Skipping acquire of configured file 'stable/binary-i386/Packages' as repository 'https://download.docker.com/linux/ubuntu xenial InRelease' doesn't support architecture 'i386'

**Comment by JohnnyQQQQ** [comment]
This issue is very low quality. 

Please consider open a new one with more information to reproduce any issue you may have faced with OS version, hetzner-kube version etc. and a description about the issue.
