### ISSUE TITLE
Addons command

### ISSUE THREAD

**Issue by pierreozoux** [xetys/hetzner-kube#18]
Should we implement an addon command, or just work on helm charts, to make them available as helm commands?

At the end, it would be one extra line. And the helm command would be more broadly used.

**Comment by xetys** [comment]
+1 for the addons command.

I wouldn't couple this too much with help as e.g. I would love to install rook from the command, and currently, the most stable way of doing this is using the pure manifests and not the chart.

Or in other words, I see a `addon helm` command to install helm with proper RBAC. I even see addon dependencies. Like "want to use `addon nginx-ingress`, it will install `addon helm` as it's a dependency"

**Comment by pierreozoux** [comment]
IMHO, if a plugin is some sort of kubernetes manifest, it should be a helm package.
Look these discussions:
 - https://github.com/kubernetes/kops/issues/2399
 - https://github.com/kubernetes/kops/issues/871
 - https://github.com/kubernetes/kops/issues/2391

If rook helm chart is not working, well, we just need to fix it :)

And if then the `addon` command is just a wrapper around helm, well, then we don't need the addon command.

I don't know myself :) But if we can avoid the extra work :)

**Comment by xetys** [comment]
I think making a wrapper around helm is a bad idea. In fact there is little to no gain for the user, use the known helm commands over hetzner-kube, if he just can `hetzner-kube cluster kubeconfig` and do it the way he want. People will more likely use helm for that.

The other point is, that we need install some software considering the circumstances of this cluster, like:

* configuring helm with rbac
* install software, which is not available or badly available in charts, like rook or prometheus
* in case of helm, providing proven values to a known chart for a better experience

The latter case would be a candidate for helm wrapping, but giving this option I pull the responsibility to this tool. My philosophy here is "use our solution as we found it working, don't change stuff and then you can expect support, or install it completely on your own". This sounds a bit harsh and static, but finally its better for both sides. Or we will end up in endless misconfigured addon issues over time. Some sort of "I installed XXX with tons of configuration and now my cluster is broken" under the title "addon doesn't work". Most commonly the user just provided false config to the target chart, but the bad guys are we ;)
