### ISSUE TITLE
use $XDG_CONFIG_HOME as config base dir

### ISSUE THREAD

**Issue by MartinNowak** [xetys/hetzner-kube#189]
To follow the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), simplify administration and backup, and avoid messy home directories.

The default for an undefined `$XDG_CONFIG_HOME` is `$HOME/.config`.

Would prolly make sense to put the config in a subfolder, i.e. `$XDG_CONFIG_HOME/hetzner-kube/config.json`. A plain file would be OK as well if chances for needing another file are slim, i.e. `$XDG_CONFIG_HOME/hetzner-kube.json`.

**Comment by mavimo** [comment]
@MartinNowak @eliasp can you test the PR reported and give me some more feedback? Thx! 🤗
