### ISSUE TITLE
MasterConfiguration should be changed to support more recent k8

### ISSUE THREAD

**Issue by rvasilev** [xetys/hetzner-kube#198]
There were a number of changes in kubeadm configuration file structure between 1.9 and 1.11 (https://github.com/kubernetes/kubernetes/pull/63788) and 1.11 to 1.12 (https://github.com/kubernetes/kubernetes/pull/65945), because of this changing of k8 version in the source (#162, #197) will not work.

The easiest workaround IMO - to bump `apiVersion: kubeadm.k8s.io/v1alpha2`, set #162 to 1.11, create cluster and after that apply [kubeadm upgrade](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-12/) to 1.12.

The more flexible way may be to templetize `master.yaml` or to provide different config generator function based on k8 version.

https://github.com/xetys/hetzner-kube/blob/034fefa2163f636d906c56a512f2dc070fbdc0b6/pkg/clustermanager/configs.go#L8-L35

And the best way will be to support latest and previous stable version of k8s.

**Comment by xetys** [comment]
This has happened in #243
