### ISSUE TITLE
Cloud-init file is not running

### ISSUE THREAD

**Issue by gadelkareem** [xetys/hetzner-kube#216]
Running the command `hetzner-kube cluster create --name demo --ssh-key demo --cloud-init cloud-init.yml`

And the cloud-init is:
```
package_upgrade: true
package_update: true
packages:
 - ceph-fs-common
 - ceph-common
 - htop
```

I see that the data is sent correctly to hcloud-go library but with no effect. Not sure where exactly is the problem.

**Comment by CuBiC3D** [comment]
Do you have `#cloud-config` as the first line? This is required.

**Comment by gadelkareem** [comment]
that fixed it thanks!
