### ISSUE TITLE
Inconsistent versioning

### ISSUE THREAD

**Issue by offlinehacker** [xetys/hetzner-kube#252]
`hetzner-kube` is kind of inconsistently versioned. It seems like `0.3.2-rc1` is latest release, but from tag name it seems like a release candidate, so i can't really deduce, which one RC and which one is latest stable release?

**Comment by xetys** [comment]
hey, thanks for the feedback.

in fact, we just missed this step. We weren't sure the 0.3.2 is really stable. But it was, and we forgot to draw a 0.3.2

the same is happening with 0.4. As I was using 0.4 for some tests with success I started a release with 0.4 as the latest stable release. It will roll out soon, so you can use this

**Comment by mavimo** [comment]
@xetys I think we can close this issue, right?

**Comment by xetys** [comment]
Sure. Finally we've got a stable 0.5 and stuff :joy:
