### ISSUE TITLE
ldflags cannot change value of a constant

### ISSUE THREAD

**Issue by kalbasit** [xetys/hetzner-kube#260]
https://github.com/xetys/hetzner-kube/blob/5f062d2ffe59aab8ae112a842b44f4ec4139efae/cmd/version.go#L10

^^ this should be `var version = "DEVELOP"` instead of a const as it cannot be set via ldflags.

```console
$ make VERSION=1.0.0 build
[ ... ]
$ ./dist/hetzner-kube-1.0.0-linux-amd64 version 
DEVELOP
```

**Comment by mavimo** [comment]
@kalbasit nice catch, thx!
