### ISSUE TITLE
Unmet dependencies on cluster create (kubernetes-cni (= 0.6.0) but 0.7.5-00 is to be installed)

### ISSUE THREAD

**Issue by cwoebker** [xetys/hetzner-kube#266]
I just tried setting up a Kubernetes cluster with Hetzner Cloud.
I ran into a similar issue as #195.

```
run failed
command:apt-get install -y docker-ce kubelet=1.13.4-00 kubeadm=1.13.4-00 kubectl=1.13.4-00 kubernetes-cni wireguard linux-headers-$(uname -r) linux-headers-virtual
stdout:Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 kubeadm : Depends: kubernetes-cni (= 0.6.0) but 0.7.5-00 is to be installed
 kubelet : Depends: kubernetes-cni (= 0.6.0) but 0.7.5-00 is to be installed
E: Unable to correct problems, you have held broken packages.

err:Process exited with status 100
```

Possible related to: https://github.com/kubernetes/kubernetes/issues/75683 &  https://github.com/kubernetes/kubernetes/issues/75701

**Comment by hyperbohlic** [comment]
@cwoebker Had the same issue. Quick fix is to change kubernetes-cni to kubernetes-cni=0.6.0-00 in /pkg/clustermanager/provision_node.go:238

**Comment by gedaiu** [comment]
I have the same issue here.

**Comment by andreymaznyak** [comment]
Any updates?

**Comment by eaydogan** [comment]
I fixed this issue on my forked repo.
If anyone interest you can get fix that repo.

https://github.com/eaydogan/hetzner-kube

Here is the commit diff:

https://github.com/eaydogan/hetzner-kube/commit/9e688d7283d1c3f209a4a7c1a0ec8b6e7211aba9

<img width="934" alt="Screen Shot 2019-04-29 at 14 38 18" src="https://user-images.githubusercontent.com/1244956/56903684-6fd6b180-6aa5-11e9-8d39-570c6b574163.png">


<img width="1159" alt="Screen Shot 2019-04-29 at 17 21 25" src="https://user-images.githubusercontent.com/1244956/56903709-7e24cd80-6aa5-11e9-86f0-ac27fad11bcb.png">

<img width="1159" alt="Screen Shot 2019-04-29 at 17 34 14" src="https://user-images.githubusercontent.com/1244956/56903744-8da41680-6aa5-11e9-9adc-0b559280b416.png">

If the project owner accepts, I can send PR for these changes.

**Comment by scasei** [comment]
Would prefer to put version strings of packages to install in a separate config file, that could be placed somewhere, if i want to overwrite compiled version strings. use case is, that i dont have to recompile the project.
