### ISSUE TITLE
cluster down because of ca.crt expiration of 1 year

### ISSUE THREAD

**Issue by lakano** [xetys/hetzner-kube#271]
Hello,
I've installed k8s with hetzner-kube one year ago, but k8s certificates have expired.
I've made a HA installation (etcd on the masters)
I've also installed rook
I've tried many solutions has explained here ( https://github.com/kubernetes/kubeadm/issues/581 ) without success.
After a reboot, I've now this error:
`The connection to the server 10.0.1.11:6443 was refused - did you specify the right host or port?
`
because he can't start kubebet:
```
Apr 06 02:52:57 infoweb-master-01 kubelet[3328]: F0406 02:52:57.038554    3328 server.go:233] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubele
Apr 06 02:52:57 infoweb-master-01 kubelet[3328]: E0406 02:52:57.037953    3328 bootstrap.go:204] Part of the existing bootstrap client certificate is expired: 2019-04-04 10:14:55 +0000 UTC
Apr 06 02:52:57 infoweb-master-01 kubelet[3328]: I0406 02:52:57.030962    3328 feature_gate.go:226] feature gates: &{{} map[]}
Apr 06 02:52:57 infoweb-master-01 kubelet[3328]: I0406 02:52:57.030287    3328 server.go:376] Version: v1.10.0
Apr 06 02:52:57 infoweb-master-01 kubelet[3328]: W0406 02:52:57.029091    3328 hostport_manager.go:68] The binary conntrack is not installed, this can cause failures in network connection cle
Apr 06 02:52:56 infoweb-master-01 kubelet[3328]: I0406 02:52:56.991720    3328 feature_gate.go:226] feature gates: &{{} map[]}
Apr 06 02:52:56 infoweb-master-01 kubelet[3328]: Flag --cadvisor-port has been deprecated, The default will change to 0 (disabled) in 1.12, and the cadvisor port will be removed entirely in 1
Apr 06 02:52:56 infoweb-master-01 kubelet[3328]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See http
Apr 06 02:52:56 infoweb-master-01 kubelet[3328]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See 
Apr 06 02:52:56 infoweb-master-01 kubelet[3328]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See http
li
```

But there is not /etc/kubernetes/bootstrap-kubelet.conf file on the master. 
Do you have any suggestion to renew the cert with hetzner-kube please ?

**Comment by kabudu** [comment]
I have also had this issue and tried a number of different solutions to no avail.

I'm strongly considering bootstrapping a new kubernetes cluster until I can find a viable solution for the future.

**Comment by lakano** [comment]
Thanks for your suggestion @kabudu , I don't really known how to do that, and as I have rook enabled for all data, is your suggestion will keep all my data please?

**Comment by kabudu** [comment]
**Disclaimer:** It wasn't a suggestion per se, but more of a statement of what I was thinking of doing. ;)

>  I don't really known how to do that, and as I have rook enabled for all data, is your suggestion will keep all my data please?

I should probably re-phrase. To solve the problem in the interim, I'm thinking of a creating a *brand new* kubernetes cluster and migrating my workloads over. That works for me as I have backups of all my data on persistent storage.

If you wanted to do this, I guess you'd have to backup your data in a suitable format, and re-import it afterwards. I'm not sure if `rook` provides simple tools for doing that, but a Google search should confirm that.

**Comment by lakano** [comment]
In fact we have everyday backup + every day snapshot of each nodes & master, but it's totally useless because I can't connect to my container to extract data... I wasn't informed of the existence of the internal certificate, and wasn't known this could be expired and couldn't permit me to retrieve my data...

**Comment by xetys** [comment]
As I had the same problem I solved it by manually downloading a recent kubeadm binary (without installing it via `apt`) and doing 

```
./kubeadm alpha certs renew all
```

and it actually worked.

About rook. I really like the way how it works, but in the end, I am not a fan of having the storage cluster inside k8s in general. The reason is quite straight forward: if k8s dies, you got issues with your storage, too. I recommend using an external solution, such as the new hetzner CSI or what I do in my clusters: ceph.

**Comment by kabudu** [comment]
> and it actually worked.

@xetys Did you perform this operation on the master only, or on the nodes as well? I just tried it on my k8 master and it didn't work, and resulted in the same error as before, i.e. `The connection to the server 10.0.1.1:6443 was refused - did you specify the right host or port?`

I tried restarting the `kube-apiserver` container but that didn't change the outcome. :/ Any ideas?

**Comment by xetys** [comment]
I did that on all masters and let the workers re join. One thing was that my monitoring still reported that the apiserver cert is expired, but it's actually not. 

In you case, I would do the following:

Get the container id by

```
docker ps -a | grep apiserver
```

You need the actual apiserver, not the pause container and then look at the log using `docker logs`.

You might also check out `journalctl -xef -u kubelet`
