### ISSUE TITLE
Is this project still maintained? 

### ISSUE THREAD

**Issue by kiloreux** [xetys/hetzner-kube#288]
Last commit was 5 months ago. And pull requests aren't being merged nor reviewed. Just want to know about a real idea on what is going on if it's no longer maintained?

**Comment by willipreuk** [comment]
I've written xetys an email, maybe he will transfer the ownership to someone.

**Comment by xetys** [comment]
hey folks,

Indeed, I had time issues all around this year. 

I'll try to find a way of bringing activity back to this project. Sorry for the delays!

**Comment by willipreuk** [comment]
Thank you!

**Comment by xetys** [comment]
for now, I'd say: yes, it's still maintained :)
