### ISSUE TITLE
Getting 2 different Kubernetes versions

### ISSUE THREAD

**Issue by MattiasGees** [xetys/hetzner-kube#306]
When doing an install from the current master branch, it mixes 2 Kubernetes versions.

When doing `kubectl version` I am getting the following:

```
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:37:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

But when doing `kubectl get nodes` I am getting this
```
NAME                   STATUS   ROLES    AGE   VERSION
kubernetes-master-01   Ready    master   35m   v1.16.2
kubernetes-worker-01   Ready    <none>   35m   v1.16.2
kubernetes-worker-02   Ready    <none>   35m   v1.16.2
```

I checked the kubeadm and kubectl package on the master server and they are both `1.16.2-00`. I think it has to do with `kubernetesVersion: stable` in `/root/master-config.yaml` when doing the `kubeadm init`. Should we fix the version in there?

**Comment by xetys** [comment]
I think you pointed it out correctly. Do you want to PR a fix for this?

**Comment by MattiasGees** [comment]
yes, I will have a look at fixing that. Trying to also think about https://github.com/xetys/hetzner-kube/issues/87 and how this fix could help towards solving this.
