### ISSUE TITLE
Hybrid clusters

### ISSUE THREAD

**Issue by Baughn** [xetys/hetzner-kube#33]
Still in the 'playing around' mode. One thing I'd like to do is build a cluster backed mostly by my own (already paid-for, fairly hefty) hardware, but with the possibility of adding worker nodes running on Hetzner on-demand.

The best way to do this, I think, would be a Kubernetes daemon that watches for overall load, creating new worker nodes when it reaches some threshold. It would make sense to use hetzner-kube for the heavy lifting.

That much should already be doable; what I'd like to ask for is the ability to link hetzner-kube to a pre-existing (non-Hetzner) cluster, and add workers to that.

There already is support for adding workers to existing clusters, so while this might be somewhat out of scope for the project, *hopefully* it wouldn't be too difficult to add. If you'd rather not, that's fine; I can probably hack something up. From the looks of config.json it might not even require any new code, but I'd like to confirm that.

(One likely stumbling block is Wireguard, which I've yet to try setting up myself. Should be fun.)

**Comment by SallySwartz** [comment]
I think it is out of scope of the project, what you are ooking for is an autoscaler if I understood well your question.

Look at this for instance:
https://github.com/kubernetes/charts/tree/master/stable/aws-cluster-autoscaler

We could imagine the same for hetzner.

**Comment by xetys** [comment]
Two thoughts on that:

1. Indeed, this project contains already some general kubernetes context which is interesting for kubernetes cluster in general. Technically this tool list tightly coupled with the hetzner API. But even that is just for the beginning part. After that the only thing needed is there IP of the server for SSH. 
I'm already thinking of some kind of refactoring, to make the actual provision part independent of the API, and works with anything what can provide server info. A yaml file, for example. This is a lot of work but enables this tool to be used in a general context.

2. You are asking for an option to provision an existing server the same way as hetzner generated. A straightforward way to do that is to add a "add-external-worker" command with an additional flag "IP" and the assumption, it has Ubuntu 16.04 with SSH available with the same key as used for the cluster. This means to build a check, which validates the provided IP to satisfy these requirement and afterwards perform the same steps like before

That is not too much work I think

**Comment by mcadam** [comment]
I would also be interested to connect current machines to a new cluster created on Hetzner. I think the road to provide an ip and a ssh key to make the connection and then apply the same scripts as the Hetzner worker ones would be nice and generic enough.

**Comment by xetys** [comment]
```
# kubectl get node 
NAME                   STATUS    ROLES     AGE       VERSION
digital-ocean-01       Ready     <none>    17m       v1.9.3
digital-ocean-02       Ready     <none>    15m       v1.9.3
level-four-master-01   Ready     master    32m       v1.9.3
level-four-master-02   Ready     master    31m       v1.9.3
level-four-worker-01   Ready     <none>    29m       v1.9.3
level-four-worker-02   Ready     <none>    29m       v1.9.3
```

Here it is, my Falkenstein-Nurenberg-London hybrid cluster. 

The PR #37 adds the option of adding any external worker node to your cluster, including wireguard handling and so on. But...

**Attention**: At the moment the hcloud-controller-manager does not recognize the new node as a listed one inside kubernetes and schedules a delete right after node-join (https://github.com/hetznercloud/hcloud-cloud-controller-manager/issues/7)

The only workaround at the moment is deleting the controller-manager:

```
# kubectl delete deployment hcloud-cloud-controller-manager -n kube-system
```

**Comment by mcadam** [comment]
Hi, I am currently trying to not add the flag "external" on the nodes that are external when we provision the node, will have a PR soon after I test it

**Comment by mcadam** [comment]
Just pushed a PR even though cant test at the moment see #40

**Comment by adrianog** [comment]
Can I create the initial ha masters on hetzner dedicated servers directly (with hetzner-lube taking care of wireguard?). Or am I forced to use hetzner cloud to bootstrap the cluster with hetzner-cube?

I have this idea of getting the wireguard part running first (on a bunch of hetzner dedicated) , then run the openshift okd  playbooks (both pre-requisites and then full openshift install): is these anything flawed in my thinking /design planning?
