### ISSUE TITLE
Removing workers

### ISSUE THREAD

**Issue by Baughn** [xetys/hetzner-kube#34]
In relation to #33, it would be useful if worker nodes could be *removed* from a cluster.

After first draining them, of course.

**Comment by JohnnyQQQQ** [comment]
For now you could use [cloud init](http://cloudinit.readthedocs.io/en/latest/topics/examples.html#additional-apt-configuration) to achieve this

**Comment by xetys** [comment]
I don't get, how this relates to cloud init. Anyway you can delete the
nodes in hetzner console, and thanks to the integrated cloud controller
manager kubernetes automatically removes that node from cluster.

But yeah, a command would be possibly better for that

Jean-Philippe Quéméner <notifications@github.com> schrieb am Do., 1. März
2018, 20:17:

**Comment by Baughn** [comment]
Yes, my request here is really to have a command that will drain a node, wait until the drain is complete and then delete the machine.

It isn't difficult to do that by hand, but it's something most people will end up needing. Maybe I'll have a stab at implementing it myself.
