### ISSUE TITLE
nginx ingress not routing traffic to service

### ISSUE THREAD

**Issue by wiemann** [xetys/hetzner-kube#53]
I installed ninx-ingress via helm 
`helm install --name ingress --set rbac.create=true,controller.kind=DaemonSet,controller.service.type=ClusterIP stable/nginx-ingress`
 but it does not route traffic to the service. Any need to configure external Ips on the hetzner-kube setup?

**Comment by wiemann** [comment]
using the `cluster addon` recipie works

**Comment by JohnnyQQQQ** [comment]
@wiemann `controller.hostNetwork=true` was missing in your set statement
