### ISSUE TITLE
Add kube-prometheus addon

### ISSUE THREAD

**Issue by JohnnyQQQQ** [xetys/hetzner-kube#54]
I just tried to monitor my cluster using prometheus and failed as kubernetes doesn't export any metrics. We should create an addon that adds an endpoint to the cluster.

**Comment by pierreozoux** [comment]
In this case, I'd advise using prometheus operator :)

it feels soo native!

**Comment by JohnnyQQQQ** [comment]
Good catch, I will give it a try!

**Comment by JohnnyQQQQ** [comment]
I changed the scope of the issue:

- [ ] Setup prometheus-operator
- [ ] Setup kube-prometheus

**Comment by xetys** [comment]
@JohnnyQQQQ I did ha manual installation. It's a hard one, but I got it working. Ping me if you need help with this

**Comment by JohnnyQQQQ** [comment]
I got a running version. Right now I try to figure out how I can monitor etcd, kube-scheduler and kube-controller. Do you have one of those up and running?

**Comment by xetys** [comment]
yes, everything but etcd, as I use it in HA and etcd is not a workload of k8s.

**Comment by JohnnyQQQQ** [comment]
Okay, did you take any special step to get the kube-scheduler and kube-controller metrics running? Somehow I don't get any targets.

**Comment by pierreozoux** [comment]
FYI, I'll work on helping to have an official helm chart for prometheus operator, if you want to help also, feel free!

https://github.com/coreos/prometheus-operator/issues/1154

**Comment by xetys** [comment]
@JohnnyQQQQ yes, use this documentation https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/docs/kube-prometheus-on-kubeadm.md

here you even can install everything as needed after the cluster installation. Then use the minikube-deploy script and it runs.

**Comment by JohnnyQQQQ** [comment]
Ah okay, I used self-hosted. Perhaps this was the problem. I will try it as soon as I have some free time.

**Comment by xetys** [comment]
This actually, cannot be the problem. Yes, there is a self-hosted flag, but it's not implemented, yet.

Maybe I should add this option :laughing:
