### ISSUE TITLE
RFE: add 'list' subcommand for 'addon'

### ISSUE THREAD

**Issue by eliasp** [xetys/hetzner-kube#59]
Right now, one has to either guess or inspect the sourcecode to get the list/names of available addons.

It would be nice to simply run:
```
hetzner-kube cluster addon list
```
…to get a list of available addons, e.g. like this:
```
NAME          REQUIRES     DESCRIPTION                               URL
helm          -            Kubernetes Package Manager                https://helm.sh
rook          -            File, Block, and Object Storage Services  https://rook.io
cert-manager  helm         Auto-TLS provisioning/management for K8S  https://github.com/jetstack/cert-manager
```

**Comment by xetys** [comment]
good hint. We need some idea to make it part of the `ClusterAddon` interface, so every addon can provide these infos by itself.
