### ISSUE TITLE
How to use CX51 VPS plan for workers please?

### ISSUE THREAD

**Issue by lakano** [xetys/hetzner-kube#66]
Hi,
Thanks for this great tool and your articles!
We've tried a default HA installation ( 4 CX11 servers, 3 masters/etcd and 1 worker ) and we would like to known how to switch worker to CX51 plan please. 

1) Can we use the Hetzner dashboard to upgrade the worker node CX11 to CX51?

2) And how can we add other workers nodes directly in CX51 please?
EDIT: Solved => cluster add-worker --worker-server-type cx51

Thanks!

**Comment by JohnnyQQQQ** [comment]
You can rescale the servers in the Hetzner dashboard.
