### ISSUE TITLE
How to expose a non-HTTP TCP port with Ingress please?

### ISSUE THREAD

**Issue by lakano** [xetys/hetzner-kube#77]
Hello!

Ingress seems to support only HTTP/HTTPS protocols ( https://github.com/kubernetes/kubernetes/issues/23291 ), and we need to expose the TCP port 3306 ( MySQL ), and restricted to an white listed IP addresses. 

Do you have any solution compatible with your hetzner-kube please?

**Comment by JohnnyQQQQ** [comment]
What is your usecase? Perhaps there is another solution for your problem.

Anyway this has nothing to do with hetzner-kube, it's about which ingress implementation you are using etc.

**Comment by lakano** [comment]
My client use the certified cash software named Pointex to manage his physical shop. He also have a PrestaShop online but as Pointex and Prestashop aren't yet connected, the online stock need to be manually updated. Pointex permit to directly update PrestaShop DB stock but of course it's require to have a connection on the TCP port 3306, we also want to secure it by restricting the access to the IP address of Pointex.

Yes it's surely more related to ingress implementation rather than hetzner-kube, but as I would like to install the Prestashop on hetzner-kube, I asked here to be sure of a compatible solution. Currently I've found kube-proxy that could may be help but as it's not used on hetzner-kube, I suppose it's not compatible.

**Comment by JohnnyQQQQ** [comment]
The clean approach would be to deploy a (micro)service that can update the stock using a RESTful interface. There you could also restrict the access etc. 

If a direct mysql connection is the only possible approach I would deploy a service using a `NodePort`. It's not recommended but it seems the only way for now. 

https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport

Blocking an IP for a certain port must also be done by hand on the node.

**Comment by lakano** [comment]
Yep I totally agree with you, but Pointex doesn't support this kind of solution.
Thanks for the link, I'll check right now! 
Regards,

**Comment by pierreozoux** [comment]
Yes, ingress is made for l7 load balancing.

For that create a service, with NodePort.
But then, yes, I'd strongly encourage to have firewall that limit per IP and also TLS and client cert auth to be extra safe!

**Comment by lakano** [comment]
Thanks @pierreozoux  ! :)

**Comment by lakano** [comment]
just for the record, there is finally TCP/UDP port forwarding support in Ingress, but this require some extra-parameters, check #79

**Comment by sam0104** [comment]
I am using port 22 and xrdp port (3389) for some services . Which is working fine in AWS with AWS LB for each exposed service . The problem in AWS it has limit for LB and I can't use more than few hundred per region.  I am looking for some solution ingress solution which can expose TCP ports like 22 , 389 and some other TCP ports .
