### ISSUE TITLE
dns issue?: heapster can't resolve node hostnames

### ISSUE THREAD

**Issue by lilvinz** [xetys/hetzner-kube#80]
I installed kubernetes-dashboard and metrics-server to get node stats. Heapster fails at resolving the worker nodes:
```
E0317 21:43:05.000376       1 summary.go:374] Node test-worker-04 has no valid hostname and/or IP address: test-worker-04
```
My understanding of kubernetes is limited and some hours of google searching didn't reveal the root cause.

Maybe this issue is related to the setup of the cluster.

**Comment by lilvinz** [comment]
It seems that heapster queries the nodeinfo and looks for Addresses.InternalIP which is not set in my cluster.

https://github.com/kubernetes-incubator/metrics-server/blob/master/metrics/sources/summary/summary.go#L402

**Comment by lilvinz** [comment]
I cannot figure out when kubelet sets InternalIP for a node. This is whats missing and makes heapster upset. Adding --node-ip=a.b.c.d to 10-kubeadm.conf doesn't seem to help either.

**Comment by xetys** [comment]
Could you please describe your setup?

**Comment by lilvinz** [comment]
Update: adding --node-ip=a.b.c.d (internal ip) does work but it seems to break the hcloud controller.

**Comment by AlexanderRay** [comment]
hello, have you solve it?

**Comment by lilvinz** [comment]
I have not been able to find a solution without side-effects. And yes, you are right, the missing InternalIP is the problem as heapster expects these to be there.

**Comment by AlexanderRay** [comment]
May be is it possible to set InternalIP during node creation?

**Comment by lilvinz** [comment]
It seems that it has been fixed upstream. When installing heapster now it just works.

**Comment by voron** [comment]
I'm still having similar issue with `mertics-server 0.3.0`, but `heapster 1.5.2` works for me in `kube-system` namespace

**Comment by tckb** [comment]
@voron  did you find a way to install metrics-server ? heapster is EOL

**Comment by voron** [comment]
@tckb no, I didn't dig in this way.

**Comment by tckb** [comment]
if you still want to, you can look into issue https://github.com/xetys/hetzner-kube/issues/289
