### ISSUE TITLE
[ rook addon ] no persistent volumes available for this claim and no storage class is set

### ISSUE THREAD

**Issue by lakano** [xetys/hetzner-kube#84]
Hi !

I'm trying to deploy my first Helm Chart on the HA cluster installed with this script. I've enable the rook addon ( require 2 times to install correctly as mentioned in another ticket ), but a call to « kubectl -n kube-system get storageClasses » confirm it's correctly installed and set as default storage.

On « kubectl get events --sort-by='{.lastTimestamp}' » I can see the exact error: FailedBinding / persistentvolume-controller / no persistent volumes available for this claim and no storage class is set.

I've tried with storageClass = "", storageClass = "default", storageClass = "standard", and storageClass = "rook-block".

Could you please help me to fix that?
Regards,

**Comment by pierreozoux** [comment]
Could you give the output of describe for PV and PVC?

**Comment by quorak** [comment]
I had a similar issue with default openebs installation. The default storageclass was not set.
I could fix it by:
```
kubectl patch storageclass openebs-standard -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
```
see: https://kubernetes.io/docs/tasks/administer-cluster/change-default-storage-class/

**Comment by lakano** [comment]
@pierreozoux The describe of pv,pvc is empty under namespace kube-sytem and there is a pvc under the default namespace in Pending named pioneering-guppy-docker-registry (but this seems related to docker-registry addon installed on the same time and not yet used)
BTW, do this mean the rook-block class need to be set as default each time for each namespace? Because for my own chart I have created a new namespace to install it.

@quorak Thanks for the idea, but the patch doesn't works « not patched », this is because it's already set by default. 

In fact the most strange thing is this doesn't works even if I set storageClass: "rook-block" :-/

**Comment by lakano** [comment]
Ok, I've just found an interesting point, this seems related to the namespace.
In the default namespace, by setting "rook-block", this works.
But if I set storageClass = "", still in the default namespace, this doesn't works ( no persistent volumes available for this claim and no storage class is set ).

**Comment by pierreozoux** [comment]
what if you don't set storage class at all?

**Comment by lakano** [comment]
@pierreozoux Same error, if set to empty string or if I remove the annotation line :(

**Comment by lakano** [comment]
May be the rook addon installation need to specify the authorization to be used on every namespaces?

**Comment by lakano** [comment]
Just figured out I've used a old annotation way ( metadata.annotations.volume.beta.kubernetes ). I've re-tested all cases with the correct way ( spec.storageClassName ), but this still doesn't works ( same error ).
More strange, in the stable way, in default namespace with "rook-block" this doesn't works anymore.

**Comment by lakano** [comment]
I would try to uninstall rook to re-install it but this give me this error:
```
2018/03/23 11:45:12 removing addon rook
2018/03/23 11:45:13 Error from server (NotFound): pools.rook.io "replicapool" not found

2018/03/23 11:45:13 > kubectl delete -n rook pool replicapool
2018/03/23 11:45:13 
2018/03/23 11:45:13 
2018/03/23 11:45:13 run failed:Process exited with status 1

```
So, even if the « get storageclass » show me « rook-block (default) », may be there is a missing piece of rook somewhere ( "replicapool not found" ) ?

**Comment by pierreozoux** [comment]
Yes, sometimes, I noticed that if you change config in rook, the better is to just recreate the cluster.
Try with a branc new cluster, I'm sure it will work.

**Comment by lakano** [comment]
@pierreozoux Ok, cluster deleted, now re-creating... thanks

**Comment by lakano** [comment]
Fixed after cluster re-creation!
Thanks for your help! :)
