### ISSUE TITLE
insuffisient cpu/memory

### ISSUE THREAD

**Issue by lakano** [xetys/hetzner-kube#85]
Hello!

I don't found any limits / quotas on new namespace created, but I have some insufficient cpu/memory when deploying a big stack.

I'm using 3x cx51 plan ( 32GB RAM / 8 CPUs ) and my helm chart dispatch on less than 96GB / 24 CPUs ( ~ 94GB / 22 CPUs ).

Is the default installation add some limits/restrictions somewhere please?

**Comment by JohnnyQQQQ** [comment]
I'm not sure what your setup is (ha, isolated etcd,...) but 2 GB Memory and 2 CPUs is probably not enough to run Kubernetes.

**Comment by lakano** [comment]
I'll try to reduce a little bit, but there is already 6GB / 6 cores for running kubernetes on the 3 masters nodes + 2 GB / 2 cores from the workers nodes.

**Comment by lakano** [comment]
I set disable some resources requests and this works now, thanks!

**Comment by xetys** [comment]
please note that disabling resource requests cannot prevent disasters in prod when you physically run out of resources. I ran in this issue a few months ago and finally realized removing these requests is a bad idea.

**Comment by lakano** [comment]
For the record, after some debug/tests, this seems to require 0.5 cpu + 1.5 GB per worker for k8s stuff.
I've tested on one cx51 server ( 32 GB / 8 cores ) mutliple cpu/memory values and this works from 30.5 GB / 7.5 cpus
