### ISSUE TITLE
Support for different OS images

### ISSUE THREAD

**Issue by kabudu** [xetys/hetzner-kube#88]
Having looked at the documentation, videos etc., I have seen Ubuntu mentioned alot in relation to the OS images for the cluster nodes. Does hetzner-kube support spinning up Hetzner Cloud servers using other OS images provided by Hetzner? e.g. the CentOS image

**Comment by pierreozoux** [comment]
@kabudu for instance, kops decided to use debian images.
I think it would be really difficult to support another base image.

**Comment by kabudu** [comment]
@pierreozoux Fair enough I guess. It's certainly not a showstopper, I just personally prefer working with CentOS, but I can live with a debian based OS.
