### ISSUE TITLE
Creation of certificates and default self-signed certs

### ISSUE THREAD

**Issue by lakano** [xetys/hetzner-kube#92]
Hi,
I've created ACME certs ( challenge http01 with « ingress: my-app-ingress-name » ), they are correctly created without error. But if I go on my browser it's still the auto-signed certs as before.
This doesn't seems to be a DNS cache problem because I've tested with another unused browser.

Could you please tell me how your script enable the self-signed certs please? May be I need to disable them, I don't known.. 

Thanks!

**Comment by xetys** [comment]
could you please describe what you mean? Certs for what? For k8s API? For a workload?

**Comment by lakano** [comment]
This was my fault, a missing TLS configuration in my ingress yaml. I believed your default configuration nginx controller take priority on 443 self-signed certs, but this was only because I've missed to add the "tls:" section in the ingress resources.
